### ISSUE TITLE
Problema de reset al volver a levantar jenkins

### ISSUE THREAD

**Issue by FranciscoCross** [javierajorge/calculator#1]
Al volver ejecutar el jenkins y probe ejecutar de nuevo un test **y no lo paso**, tuve que volver a instalar el paquete build-essential y anduvo, resolver para que quede guardado el paquete en el server!! (prueba de issue)

**Comment by javierbrk** [comment]
Confirmado, pude reproducir el problema la apagar y volver a encender la imagen de docker

**Comment by javierbrk** [comment]
@FranciscoCross acabo de hacer un commit con un nuevo instructivo, seguí las instrucciones y si con eso podes resolver el problema podes cerrar este issue.

**Comment by FranciscoCross** [comment]
Bien ya pruebo profe!!!

**Comment by FranciscoCross** [comment]
Buenas profe, disculpe la hora, pude arreglar el problema siguien estos pasos

- quite --rm del comando para crear el server (comando que sirve para borrar una vez que es detenido la imagen)
- luego pare el container con " docker container stop jenkins_server"
- lo volvi a ejecutar con "sudo docker start jenkins_server"

Todo esto con los paquetes instaldos en jenkins y demas, anduvo perfecto!!!
